db:
  host: localhost
  port: 5434
  username: postgres
  password: postgres
  db_name: order_service_wb_db
  ssl_mode: disable

server:
  port: "8081"

cache:
  size: 10

kafka:
  broker: "localhost:9092"
  topic: "order"
  group: "order-group"
