services:
  db:
    container_name: order-service-wb-db
    image: postgres:17.5
    env_file: .env
    restart: always
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 30

  kafka:
    container_name: order-service-wb-kafka
    image: confluentinc/cp-kafka:7.7.1.amd64
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: 'FzQ9ZTNmODY1OWE0RGAmMD'
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:29092" ]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-ui:
    container_name: order-service-wb-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"

  kafka-init-topics:
    container_name: order-service-wb-init-topics
    image: confluentinc/cp-kafka:7.7.1.amd64
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
            cub kafka-ready -b kafka:29092 1 60 && \
            kafka-topics --create --topic order --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092'"

